'use client';
import {useEffect,useState} from 'react';
import {Heart,ChefHat,BookOpen,Users,UserRound,ArrowUpRight,ArrowRight,Camera,Plus,Headphones,MessageCircle,ChevronRight,ShoppingBag,Check,UtensilsCrossed,LoaderCircle,Sparkles,X,LogOut,Phone,Clock,Flame} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Sheet,SheetClose,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import curated from './recipes.json';
import innovation from './innovation.json';
import ig from './ig.json';
import Studio from './studio';
import RecipePreparation from './recipe-preparation';
import PhoneAuth,{type KitchenUser} from './phone-auth';
type Recipe=typeof curated[number]&{story?:string;time?:string;servings?:string};
const recipes:Recipe[]=[...curated,...ig,...innovation];
const igIds=new Set(ig.map(r=>r.id));
export type Post={id:string;title:string;description:string;author:string;image:string;createdAt:number;mine:boolean};
const products=[{id:'vermicelli',name:'龍口粉絲',note:'幼滑掛汁，點煮都啱。',image:'vermicelli.png'},{id:'crystal',name:'水晶粉皮',note:'晶瑩煙韌，涼拌一流。',image:'crystal.png'},{id:'wide',name:'綠豆馬鈴薯寬粉',short:'馬鈴薯寬粉',note:'薄身爽滑，煲仔好拍檔。',image:'wide.png'},{id:'nori',name:'精選紫菜',note:'啖啖鮮香，屋企嘅味道。',image:'nori.jpg'}];
export default function Kitchen({user:initialUser}:{user:KitchenUser|null}){
 const [user,setUser]=useState(initialUser),[authOpen,setAuthOpen]=useState(false),[resumeStudio,setResumeStudio]=useState(false),[tab,setTab]=useState('recipes'),[product,setProduct]=useState('all'),[selected,setSelected]=useState<Recipe|null>(null),[post,setPost]=useState<Post|null>(null),[studio,setStudio]=useState(false),[saved,setSaved]=useState<string[]>([]),[posts,setPosts]=useState<Post[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[saveBusy,setSaveBusy]=useState<string[]>([]),[completed,setCompleted]=useState<number[]>([]),[accountView,setAccountView]=useState('saved');
 async function refresh(){setLoading(true);setError('');try{const r=await fetch('/api/posts');const data=await r.json() as {posts:Post[];error?:string};if(!r.ok)throw new Error(data.error);setPosts(data.posts);}catch(e){setError(e instanceof Error?e.message:'暫時載入唔到，請再試。');}finally{setLoading(false)}}
 async function refreshFavorites(){try{const r=await fetch('/api/favorites');const d=await r.json() as {error?:string;favorites:string[]};if(!r.ok)throw new Error(d.error);setSaved(d.favorites)}catch(e){toast.error(e instanceof Error?e.message:'暫時載入唔到收藏。')}}
 useEffect(()=>{refresh();refreshFavorites()},[]);
 function requireStudioLogin(){setResumeStudio(true);setStudio(false);setAuthOpen(true)}
 function startCommunity(){if(!user){toast('先登記一個帳戶，就可以分享你嘅拿手菜。');requireStudioLogin()}else setStudio(true)}
 function openRecipe(r:Recipe){setSelected(r);setCompleted([])}
 async function favorite(item:string){if(!user){setAuthOpen(true);return}if(saveBusy.includes(item))return;setSaveBusy(v=>[...v,item]);try{const next=!saved.includes(item);const r=await fetch('/api/favorites',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({item,saved:next})});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error);setSaved(v=>next?[...v,item]:v.filter(x=>x!==item));toast.success(next?'已收藏，下次煮返呢味！':'已取消收藏');}catch(e){toast.error(e instanceof Error?e.message:'儲存唔到，請再試。')}finally{setSaveBusy(v=>v.filter(x=>x!==item))}}
 async function logout(){if(user?.source==='platform'){window.location.href='/signout-with-chatgpt?return_to=/';return}try{const r=await fetch('/api/auth/logout',{method:'POST'});if(!r.ok)throw new Error();setUser(null);setSaved([]);refresh();toast.success('已登出帳戶。')}catch{toast.error('暫時登出唔到，請再試一次。')}}
 function heart(item:string){return <button className={'heart '+(saved.includes(item)?'is-saved':'')} aria-label={saved.includes(item)?'取消收藏':'收藏食譜'} aria-pressed={saved.includes(item)} disabled={saveBusy.includes(item)} onClick={e=>{e.stopPropagation();favorite(item)}}><Heart size={19} fill={saved.includes(item)?'currentColor':'none'}/></button>}
 function recipeCard(r:Recipe){return <article className="recipe-card" key={r.id}><div className="recipe-photo"><button onClick={()=>openRecipe(r)} aria-label={'睇'+r.name+'嘅做法'}><img src={r.image} alt={r.name} loading="lazy"/></button>{heart('r:'+r.id)}<span className="photo-tag">{r.category}</span></div><button className="recipe-info" onClick={()=>openRecipe(r)}><div className="recipe-product">{r.products.map(p=>products.find(x=>x.id===p)?.short||products.find(x=>x.id===p)?.name).join(' · ')}</div><h3>{r.name}</h3><div className="recipe-meta"><span>{r.steps.length} 個步驟</span><span>睇做法 <ArrowUpRight size={16}/></span></div></button></article>}
 function postCard(p:Post){return <article className="recipe-card community-card" key={p.id}><div className="recipe-photo"><button onClick={()=>setPost(p)} aria-label={'睇'+p.title}><img src={p.image} alt={p.title} loading="lazy"/></button>{heart('p:'+p.id)}</div><button className="recipe-info" onClick={()=>setPost(p)}><h3>{p.title}</h3><div className="recipe-meta"><span><UserRound size={14}/>{p.author}</span><span>廚神打卡</span></div></button></article>}
 const shown=curated.filter(r=>product==='all'||r.products.includes(product));
 return <><Toaster position="top-center"/><Tabs value={tab} onValueChange={v=>{setTab(v);window.scrollTo({top:0,behavior:'smooth'})}} className="app-tabs"><header className="site-header"><div className="header-inner"><button className="brand" onClick={()=>setTab('recipes')} aria-label="返回玖柒廚房主頁"><img src="/assets/logo.jpg" alt="玖柒牌"/><strong>玖柒廚房</strong></button><TabsList className="main-nav"><TabsTrigger value="recipes"><BookOpen/>精選食譜</TabsTrigger><TabsTrigger value="innovation"><Sparkles/>創新菜式</TabsTrigger><TabsTrigger value="ig"><Flame/>IG博主同款</TabsTrigger><TabsTrigger value="community"><Users/>共創菜品</TabsTrigger><TabsTrigger value="account"><UserRound/>我的帳戶</TabsTrigger></TabsList><button className="header-create" onClick={()=>setStudio(true)} aria-label="製作廚神打卡相"><Camera size={18}/><span>廚神打卡</span></button></div></header>
 <main><TabsContent value="recipes"><div className="intro"><div><h1>今日，煮返餐<em>靚嘅。</em></h1><p>一包玖柒，百變好滋味。揀好食材，就開飯。</p></div><button className="studio-banner" onClick={()=>setStudio(true)}><Camera size={26}/><div><strong>你嘅拿手菜，值得打卡。</strong><span>整張專屬廚神相 <ArrowUpRight size={18}/></span></div></button></div>
 <section className="product-section" aria-label="按食材揀食譜"><div className="section-top"><h2>由好食材開始</h2><button className={'all-button '+(product==='all'?'active':'')} onClick={()=>setProduct('all')}>全部食材 <ArrowUpRight size={16}/></button></div><div className="product-grid">{products.map(p=><button key={p.id} className={'product-card '+(product===p.id?'selected':'')} aria-pressed={product===p.id} onClick={()=>setProduct(product===p.id?'all':p.id)}><img src={'/assets/'+p.image} alt={'玖柒牌'+p.name}/><div><h3>{p.short||p.name}</h3><p>{p.note}</p><span>{curated.filter(r=>r.products.includes(p.id)).length} 道食譜</span></div>{product===p.id&&<span className="product-check"><Check size={14}/></span>}</button>)}</div></section>
 <section className="recipe-section"><div className="section-top collection-heading"><div><h2>{product==='all'?'日常好煮意':(products.find(p=>p.id===product)?.short||products.find(p=>p.id===product)?.name)+'好煮意'}</h2><p>簡單跟住煮，屋企都食得精彩。</p></div><span className="collection-count">{shown.length} 道精選食譜</span></div><div className="recipe-grid featured-grid">{shown.map(recipeCard)}</div></section></TabsContent>
 <TabsContent value="innovation"><div className="innovation-intro"><span className="innovation-label"><Sparkles size={16}/> 玖柒新煮意</span><h1>熟悉嘅食材，<br/><em>煮啲唔同嘅。</em></h1><p>金沙鹹香、薄荷清新、濃茄芝士。<br className="mobile-break"/>三款原創配搭，畀日常餐桌一啲驚喜。</p></div><div className="innovation-list">{innovation.map((r,i)=><article key={r.id} className={'innovation-story story-'+i}><button className="innovation-image" onClick={()=>openRecipe(r)} aria-label={'睇'+r.name+'嘅做法'}><img src={r.image} alt={r.name}/></button><div className="innovation-copy"><div className="innovation-category">{r.category}</div><h2>{r.name}</h2><p>{r.story}</p><div className="innovation-details"><span><Clock size={16}/>{r.time}</span><span><Users size={16}/>{r.servings}</span></div><div className="innovation-actions"><button className="primary" onClick={()=>openRecipe(r)}>試煮呢一道 <ArrowUpRight size={18}/></button>{heart('r:'+r.id)}</div></div></article>)}</div></TabsContent>
 <TabsContent value="ig"><div className="innovation-intro"><span className="innovation-label"><Flame size={16}/> IG博主同款</span><h1>IG 見到嘅，<br/><em>今晚煮得返。</em></h1><p>博主同款人氣蒸菜，<br className="mobile-break"/>粉絲吸滿蒜香，蚌肉鮮甜彈牙。</p></div><div className="innovation-list">{ig.map((r,i)=><article key={r.id} className={'innovation-story story-'+i}><button className="innovation-image" onClick={()=>openRecipe(r)} aria-label={'睇'+r.name+'嘅做法'}><img src={r.image} alt={r.name}/></button><div className="innovation-copy"><div className="innovation-category">{r.category}</div><h2>{r.name}</h2><p>{r.story}</p><div className="innovation-details"><span><Clock size={16}/>{r.time}</span><span><Users size={16}/>{r.servings}</span></div><div className="innovation-actions"><button className="primary" onClick={()=>openRecipe(r)}>試煮呢一道 <ArrowUpRight size={18}/></button>{heart('r:'+r.id)}</div></div></article>)}</div></TabsContent>
 <TabsContent value="community"><div className="intro"><div><h1>好味道，<em>一齊煮出嚟。</em></h1><p>分享你嘅拿手菜，有機會入選「精選食譜」。</p></div><button className="primary" onClick={startCommunity}><Camera size={19}/>製作廚神打卡相</button></div>{loading?<div className="empty"><LoaderCircle className="spin"/>搵緊好味道…</div>:error?<div className="empty"><p>{error}</p><button className="secondary" onClick={refresh}>再試一次</button></div>:posts.length?<div className="recipe-grid">{posts.map(postCard)}</div>:<div className="community-empty"><UtensilsCrossed size={44}/><h2>第一道好菜，等你上枱。</h2><p>影低你嘅拿手菜，將煮食靈感分享畀大家。</p><button className="primary" onClick={startCommunity}><Plus size={18}/>分享我嘅第一道菜</button></div>}</TabsContent>
 <TabsContent value="account"><div className="account-header"><div className="avatar"><ChefHat size={32}/></div><div><h1>{user?user.name:'呢度係你嘅廚房。'}</h1><p>{user?(user.phone?`已驗證手機 ${user.phone}`:'收藏好煮意，記低每次好味道。'):'登記帳戶，儲起心頭好，分享廚神時刻。'}</p></div>{!user?<button className="primary" onClick={()=>setAuthOpen(true)}>登記／登入 <ArrowRight size={18}/></button>:<div className="account-auth-actions">{user.source==='platform'&&<button className="text-button" onClick={()=>setAuthOpen(true)}><Phone size={16}/>手機登記</button>}<button className="text-button" onClick={logout}><LogOut size={16}/>登出</button></div>}</div><div className="account-services"><button onClick={()=>toast('客戶服務，敬請期待。')}><Headphones/><span>聯絡客服<small>有問題，我哋樂意幫手。</small></span><ChevronRight/></button><button onClick={()=>toast('WhatsApp 福利群，敬請期待。')}><MessageCircle/><span>WhatsApp 福利群<small>好味道同專屬優惠，即將送上。</small></span><ChevronRight/></button></div><Tabs value={accountView} onValueChange={setAccountView} className="account-content"><TabsList><TabsTrigger value="saved">我的收藏 · {saved.length}</TabsTrigger><TabsTrigger value="mine">我的打卡 · {posts.filter(p=>p.mine).length}</TabsTrigger></TabsList><TabsContent value="saved">{saved.length?<div className="recipe-grid">{recipes.filter(r=>saved.includes('r:'+r.id)).map(recipeCard)}{posts.filter(p=>saved.includes('p:'+p.id)).map(postCard)}</div>:<div className="empty"><Heart size={34}/><h3>心頭好，留返下次煮。</h3><p>撳食譜上嘅心心，就可以儲喺呢度。</p><button className="secondary" onClick={()=>setTab('recipes')}>睇吓精選食譜 <ArrowRight size={16}/></button></div>}</TabsContent><TabsContent value="mine">{posts.some(p=>p.mine)?<div className="recipe-grid">{posts.filter(p=>p.mine).map(postCard)}</div>:<div className="empty"><Camera size={34}/><h3>第一個廚神時刻，由你開始。</h3><button className="primary" onClick={()=>setStudio(true)}>製作打卡相</button></div>}</TabsContent></Tabs></TabsContent></main><footer className="footer"><div><img src="/assets/logo.jpg" alt=""/><strong>玖柒廚房</strong></div><span>好食材，好好煮，好好食。</span></footer></Tabs>
 <Sheet open={!!selected||!!post} onOpenChange={open=>{if(!open){setSelected(null);setPost(null)}}}><SheetContent className="recipe-detail" showCloseButton={false}><SheetClose className="close-button" aria-label="關閉食譜"><X size={20}/></SheetClose>{selected?<><div className="detail-photo"><img src={selected.image} alt={selected.name}/><span>{igIds.has(selected.id)?'玖柒 · IG博主同款':selected.id>27?'玖柒 · 創新菜式':'玖柒 · 精選食譜'}</span></div><div className="detail-body"><div className="detail-title"><SheetTitle>{selected.name}</SheetTitle>{heart('r:'+selected.id)}</div><SheetDescription>{selected.time?`${selected.time} · ${selected.servings} · `:''}{selected.steps.length} 個步驟，跟住煮就得。</SheetDescription><RecipePreparation key={selected.id} ingredients={selected.ingredients} seasoning={selected.seasoning} steps={selected.steps} tips={selected.tips}/><div className="used-products">{products.filter(p=>selected.products.includes(p.id)).map(p=><button key={p.id} onClick={()=>{setProduct(p.id);setTab('recipes');setSelected(null)}}><img src={'/assets/'+p.image} alt=""/><span>呢道菜用到<strong>{p.name}</strong></span><ArrowUpRight size={18}/></button>)}</div></div><div className="detail-buy"><button className="primary" onClick={()=>toast('ESG 商城，敬請期待。')}><ShoppingBag size={19}/>一鍵買同款，送貨到屋企</button></div></>:post?<><img className="post-detail-image" src={post.image} alt={post.title}/><div className="detail-body"><div className="detail-title"><SheetTitle>{post.title}</SheetTitle>{heart('p:'+post.id)}</div><SheetDescription>{post.author} · {new Date(post.createdAt).toLocaleDateString('zh-HK')} · 共創菜品</SheetDescription>{post.description&&<div className="post-description"><h3>我嘅煮食心得</h3><p>{post.description}</p></div>}<p className="selection-note">好菜值得畀人見到，呢份作品有機會入選「精選食譜」。</p></div></>:null}</SheetContent></Sheet>
 <Studio open={studio} onOpenChange={setStudio} user={!!user} onLogin={requireStudioLogin} onPublished={()=>{refresh();setTab('community')}}/>
 <PhoneAuth open={authOpen} onOpenChange={v=>{setAuthOpen(v);if(!v&&resumeStudio){setStudio(true);setResumeStudio(false)}}} onSuccess={u=>{setUser(u);if(resumeStudio){setStudio(true);setResumeStudio(false)}refreshFavorites();refresh();toast.success('歡迎返嚟，'+u.name+'！')}}/>
 </>;
}
