'use client';
import {useState} from 'react';
import {ArrowRight,Eye,EyeOff,LoaderCircle,LockKeyhole} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import type {KitchenUser} from './phone-auth';
export default function PasswordForm({onSuccess}:{onSuccess:(user:KitchenUser)=>void}){
 const [mode,setMode]=useState('register'),[name,setName]=useState(''),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[visible,setVisible]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(e:React.FormEvent){e.preventDefault();setError('');if(mode==='register'&&password!==confirm){setError('兩次輸入嘅密碼唔一致。');return}setBusy(true);try{const r=await fetch('/api/auth/password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode,name,username,password})});const data=await r.json() as {user:KitchenUser;error?:string};if(!r.ok)throw new Error(data.error||'登入唔成功，請再試。');setPassword('');setConfirm('');onSuccess(data.user)}catch(e){setError(e instanceof Error?e.message:'請稍後再試。')}finally{setBusy(false)}}
 return <><Tabs value={mode} onValueChange={v=>{setMode(v);setError('')}} className="password-modes"><TabsList><TabsTrigger value="register">新會員登記</TabsTrigger><TabsTrigger value="login">已有帳戶</TabsTrigger></TabsList></Tabs><form className="auth-fields password-fields" onSubmit={submit}>{mode==='register'&&<><label htmlFor="password-name">點稱呼你？</label><input id="password-name" autoComplete="nickname" required maxLength={24} placeholder="你嘅主廚名" value={name} onChange={e=>setName(e.target.value)}/></>}<label htmlFor="login-username">登入名稱</label><input id="login-username" autoComplete="username" autoCapitalize="none" spellCheck={false} required minLength={4} maxLength={32} pattern="[A-Za-z0-9][A-Za-z0-9_.\-]{3,31}" placeholder="4–32 個英文字母、數字或 . _ -" value={username} onChange={e=>setUsername(e.target.value)}/><label htmlFor="login-password">密碼</label><div className="password-input"><input id="login-password" type={visible?'text':'password'} autoComplete={mode==='register'?'new-password':'current-password'} required minLength={10} maxLength={64} placeholder="最少 10 個字元" value={password} onChange={e=>setPassword(e.target.value)}/><button type="button" aria-label={visible?'隱藏密碼':'顯示密碼'} aria-pressed={visible} onClick={()=>setVisible(v=>!v)}>{visible?<EyeOff size={19}/>:<Eye size={19}/>}</button></div>{mode==='register'&&<><label htmlFor="confirm-password">再輸入一次密碼</label><input id="confirm-password" type={visible?'text':'password'} autoComplete="new-password" required minLength={10} maxLength={64} value={confirm} onChange={e=>setConfirm(e.target.value)}/><p className="auth-privacy">稱呼會顯示喺你嘅帳戶同共創作品。請記低登入名稱及密碼；目前未提供自助重設密碼。</p></>}{error&&<p className="error-text" role="alert">{error}</p>}<button className="primary full" disabled={busy} type="submit">{busy?<LoaderCircle className="spin" size={18}/>:<LockKeyhole size={18}/>} {mode==='register'?'建立帳戶，繼續煮':'登入，繼續煮'}<ArrowRight size={18}/></button></form></>
}
