'use client';
import {useEffect,useState} from 'react';
import {ArrowLeft,ArrowRight,LoaderCircle,Phone,X} from 'lucide-react';
import {Dialog,DialogClose,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {InputOTP,InputOTPGroup,InputOTPSlot} from '@/components/ui/input-otp';
import {Checkbox} from '@/components/ui/checkbox';
import PasswordForm from './password-form';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {countryCodes,normalizePhone} from '@/lib/phone';
export type KitchenUser={name:string;phone:string|null;source:'phone'|'platform'|'password'};
export default function PhoneAuth({open,onOpenChange,onSuccess}:{open:boolean;onOpenChange:(open:boolean)=>void;onSuccess:(user:KitchenUser)=>void}){
 const [method,setMethod]=useState('password');
 const [country,setCountry]=useState('852'),[phone,setPhone]=useState(''),[name,setName]=useState(''),[consent,setConsent]=useState(false),[challenge,setChallenge]=useState(''),[code,setCode]=useState(''),[seconds,setSeconds]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[enabled,setEnabled]=useState<boolean|null>(null);
 useEffect(()=>{if(!open||method!=='phone')return;fetch('/api/auth/status').then(async r=>{if(!r.ok)throw new Error();const d=await r.json() as {smsEnabled:boolean};setEnabled(d.smsEnabled)}).catch(()=>{setEnabled(false);setError('暫時連接唔到登記服務，請稍後再試。')})},[open,method]);
 useEffect(()=>{if(seconds<=0)return;const id=setTimeout(()=>setSeconds(s=>s-1),1000);return ()=>clearTimeout(id)},[seconds]);
 async function send(){setError('');if(!normalizePhone(country,phone)){setError('請檢查區號同手機號碼。');return}if(!name.trim()||!consent){setError('請填上稱呼，並同意接收登入驗證短訊。');return}setBusy(true);try{const r=await fetch('/api/auth/send-code',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({country,phone,name,consent})});const d=await r.json() as {error?:string;challengeId:string;retryAfter:number};if(!r.ok)throw new Error(d.error||'未能發出驗證碼，請再試。');setChallenge(d.challengeId);setCode('');setSeconds(d.retryAfter)}catch(e){setError(e instanceof Error?e.message:'短訊發唔到，請稍後再試。')}finally{setBusy(false)}}
 async function verify(){setBusy(true);setError('');try{const r=await fetch('/api/auth/verify-code',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({challengeId:challenge,code})});const d=await r.json() as {error?:string;user:KitchenUser};if(!r.ok)throw new Error(d.error||'驗證唔成功，請再試。');onSuccess(d.user);onOpenChange(false);setChallenge('');setCode('')}catch(e){setError(e instanceof Error?e.message:'驗證唔成功，請再試。')}finally{setBusy(false)}}
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="auth-dialog" showCloseButton={false}><DialogClose className="close-button" aria-label="關閉會員登記"><X size={20}/></DialogClose><div className="auth-mark"><img src="/assets/logo.jpg" alt="玖柒牌"/></div><DialogTitle>{method==='phone'&&challenge?'輸入驗證碼':'留低你嘅拿手好味'}</DialogTitle><DialogDescription>{method==='phone'&&challenge?`短訊已發送至 +${country} ${phone}。請輸入六位驗證碼。`:'登記或登入，收藏食譜、分享你嘅廚神時刻。'}</DialogDescription><Tabs value={method} onValueChange={setMethod} className="auth-methods"><TabsList><TabsTrigger value="password">帳戶及密碼</TabsTrigger><TabsTrigger value="phone">手機驗證碼</TabsTrigger></TabsList></Tabs>{method==='password'?<PasswordForm onSuccess={u=>{onSuccess(u);onOpenChange(false)}}/>:<>{!challenge?<form onSubmit={e=>{e.preventDefault();send()}} className="auth-fields"><label htmlFor="member-name">點稱呼你？</label><input id="member-name" autoComplete="nickname" maxLength={24} value={name} onChange={e=>setName(e.target.value)} placeholder="輸入你嘅主廚名"/><label htmlFor="member-phone">手機號碼</label><div className="phone-row"><Select value={country} onValueChange={setCountry}><SelectTrigger aria-label="電話區號"><SelectValue/></SelectTrigger><SelectContent>{countryCodes.map(c=><SelectItem key={c.code} value={c.code}>{c.name} +{c.code}</SelectItem>)}</SelectContent></Select><input id="member-phone" type="tel" autoComplete="tel-national" inputMode="tel" placeholder="手機號碼" value={phone} maxLength={18} onChange={e=>setPhone(e.target.value)}/></div><label className="consent-label"><Checkbox checked={consent} onCheckedChange={v=>setConsent(v===true)}/><span>我同意接收今次登入所需嘅驗證短訊。手機號碼只用作帳戶驗證，唔會公開。</span></label><p className="auth-privacy">完成驗證後會建立會員記錄，儲存你嘅稱呼、手機號碼、收藏及打卡作品。</p>{enabled===false&&<p className="service-pending" role="status">手機登記即將開放。你可以先睇食譜，同埋製作及下載打卡相。</p>}<button className="primary full" type="submit" disabled={busy||enabled!==true||!consent||!name.trim()||!phone.trim()}>{busy?<LoaderCircle className="spin" size={18}/>:<Phone size={18}/>} {enabled===null?'正在連接…':enabled===false?'短訊驗證尚未啟用':'發送驗證碼'}<ArrowRight size={18}/></button></form>:<form onSubmit={e=>{e.preventDefault();verify()}} className="otp-form"><InputOTP aria-label="六位短訊驗證碼" maxLength={6} pattern="^[0-9]*$" inputMode="numeric" autoComplete="one-time-code" value={code} onChange={setCode}><InputOTPGroup>{Array.from({length:6},(_,i)=><InputOTPSlot key={i} index={i}/>)}</InputOTPGroup></InputOTP><button className="primary full" type="submit" disabled={code.length!==6||busy}>{busy&&<LoaderCircle className="spin" size={18}/>}驗證並登入 <ArrowRight size={18}/></button><button type="button" className="text-button" disabled={seconds>0||busy} onClick={send}>{seconds>0?`${seconds} 秒後可重新發送`:'重新發送驗證碼'}</button><button type="button" className="text-button" onClick={()=>{setChallenge('');setError('')}}><ArrowLeft size={16}/>修改手機號碼</button></form>}{error&&<p role="alert" className="error-text">{error}</p>}</>}</DialogContent></Dialog>
}
