'use client';
import {useState} from 'react';
import {Check,Carrot,Fish,Wheat,Leaf,Milk,Flame,Timer,UtensilsCrossed,ChefHat,Droplets,Lightbulb,ShoppingBasket} from 'lucide-react';
import {Checkbox} from '@/components/ui/checkbox';
import {Progress} from '@/components/ui/progress';
export function splitIngredients(text:string){const out:string[]=[];let depth=0,current='';for(const c of text){if('（('.includes(c))depth++;if('）)'.includes(c))depth=Math.max(0,depth-1);if(depth===0&&'、，,；;\n'.includes(c)){if(current.trim())out.push(current.trim());current=''}else current+=c}if(current.trim())out.push(current.trim());return out}
function foodIcon(s:string){if(/蝦|魚|蟹|海鮮|蜆/.test(s))return Fish;if(/粉|飯|麵/.test(s))return Wheat;if(/奶|芝士|蛋/.test(s))return Milk;if(/菜|蔥|芫荽|薄荷/.test(s))return Leaf;if(/油|水|醋|汁|酒/.test(s))return Droplets;return Carrot}
function stepInfo(s:string){if(/蒸|煮|煲|燜|燴|炒|焗|煎/.test(s))return {Icon:Flame,label:'掌握火候'};if(/浸|醃|分鐘/.test(s))return {Icon:Timer,label:'俾啲時間'};if(/盛|上碟|撒|淋/.test(s))return {Icon:UtensilsCrossed,label:'靚靚上碟'};return {Icon:ChefHat,label:'備好食材'}}
export default function RecipePreparation({ingredients,seasoning,steps,tips}:{ingredients:string;seasoning:string;steps:string[];tips:string}){
 const [ready,setReady]=useState<string[]>([]),[done,setDone]=useState<number[]>([]);
 const items=splitIngredients(ingredients),sauces=splitIngredients(seasoning);
 return <><section className="mise-en-place"><div className="prep-section-title"><ShoppingBasket size={24}/><div><h3>好味，由備料開始</h3><p>撳一下，記低已備好嘅食材。</p></div><span>{ready.length}/{items.length+sauces.length}</span></div>{[[items,'主要食材'],[sauces,'調味配搭']].map(([list,label],section)=><div className="ingredient-section" key={section}><h4>{label as string}</h4><ul>{(list as string[]).map((item,i)=>{const key=section+':'+i,Icon=foodIcon(item);return <li key={key} className={ready.includes(key)?'ready':''}><label><Icon size={19} strokeWidth={1.5}/><span>{item}</span><Checkbox aria-label={'已備好'+item} checked={ready.includes(key)} onCheckedChange={checked=>setReady(v=>checked?[...v,key]:v.filter(x=>x!==key))}/></label></li>})}</ul></div>)}</section>{tips&&<aside className="chef-tip"><Lightbulb size={22}/><div><h4>主廚小貼士</h4><p>{tips}</p></div></aside>}<section className="cooking-method"><div className="prep-section-title"><UtensilsCrossed size={24}/><div><h3>跟住煮，慢慢嚟。</h3><p aria-live="polite">{done.length===steps.length?'完成喇，開飯！':`已完成 ${done.length} 個步驟`}</p></div><span>{done.length}/{steps.length}</span></div><Progress aria-label="煮食進度" value={done.length/steps.length*100} className="cooking-progress"/><ol className="method-timeline">{steps.map((step,i)=>{const {Icon,label}=stepInfo(step),complete=done.includes(i);return <li key={i} className={complete?'complete':''}><button className="step-marker" aria-label={(complete?'取消完成':'完成')+'步驟 '+(i+1)} aria-pressed={complete} onClick={()=>setDone(v=>complete?v.filter(n=>n!==i):[...v,i])}>{complete?<Check size={19}/>:String(i+1).padStart(2,'0')}</button><div className="method-copy"><div className="method-label"><Icon size={16}/><span>{label}</span><button onClick={()=>setDone(v=>complete?v.filter(n=>n!==i):[...v,i])}>{complete?'已完成':'完成呢步'}<Check size={14}/></button></div><p>{step}</p></div></li>})}</ol></section></>
}
