import { sqliteTable, text, integer, primaryKey, index } from 'drizzle-orm/sqlite-core';
export const posts = sqliteTable('posts', { id: text('id').primaryKey(), owner: text('owner').notNull(), author: text('author').notNull(), title: text('title').notNull(), description: text('description').notNull(), imageKey: text('image_key').notNull(), createdAt: integer('created_at').notNull() }, t => [index('idx_posts_created_at').on(t.createdAt)]);
export const favorites = sqliteTable('favorites', { owner: text('owner').notNull(), item: text('item').notNull() }, t => [primaryKey({columns:[t.owner,t.item]})]);
export const members = sqliteTable('members', { id: text('id').primaryKey(), phone: text('phone').notNull().unique(), displayName: text('display_name').notNull(), createdAt: integer('created_at').notNull(), lastLoginAt: integer('last_login_at').notNull() });
export const memberSessions = sqliteTable('member_sessions', { tokenHash: text('token_hash').primaryKey(), memberId: text('member_id').notNull().references(()=>members.id), expiresAt: integer('expires_at').notNull() }, t=>[index('idx_sessions_member').on(t.memberId)]);
export const phoneChallenges = sqliteTable('phone_challenges', { id: text('id').primaryKey(), phone: text('phone').notNull(), displayName: text('display_name').notNull(), attempts: integer('attempts').notNull().default(0), consumed: integer('consumed').notNull().default(0), expiresAt: integer('expires_at').notNull() });
export const authLimits = sqliteTable('auth_limits', { key: text('key').primaryKey(), count: integer('count').notNull(), resetsAt: integer('resets_at').notNull() });
export const passwordAccounts = sqliteTable('password_accounts', {id:text('id').primaryKey(), username:text('username').notNull().unique(), displayName:text('display_name').notNull(), passwordHash:text('password_hash').notNull(), createdAt:integer('created_at').notNull()});
export const passwordSessions = sqliteTable('password_sessions', {tokenHash:text('token_hash').primaryKey(), accountId:text('account_id').notNull().references(()=>passwordAccounts.id), expiresAt:integer('expires_at').notNull()},t=>[index('idx_password_sessions_account').on(t.accountId)]);
